### ISSUE TITLE
Multi threading does not use all available resources

### ISSUE THREAD

**Issue by hrt** [ih1115/Patching#2]

**Comment by hrt** [comment]
Multi threading won't be so useful anyway if we implement an intelligent algorithm

**Comment by JPalchak** [comment]
What happened to the Multi-Threading? I can only load one of my threads. I don't see how it wouldn't be useful for this approach.

**Comment by hrt** [comment]
For this (very bad) approach it'd be good.

If you have a little intelligence like some longest path algorithm, it's not needed.
